import {
  AdminOrder,
  FestivalCampaign,
  Coupon,
  TableBooking,
  CustomerCRM,
  StaffMember,
  InventoryItem,
  ActivityLog,
} from './types';

export const INITIAL_ORDERS: AdminOrder[] = [
  {
    id: 'ORD-8942',
    customerName: 'Rajesh Sharma',
    customerPhone: '+91 98765 43210',
    customerEmail: 'rajesh.s@gmail.com',
    deliveryAddress: 'B-402, Royal Palms, Connaught Place, New Delhi',
    items: [
      { id: '1', sweetName: 'Kaju Katli Special', quantityKg: 2, pricePerKg: 1100, totalPrice: 2200 },
      { id: '2', sweetName: 'Motichoor Laddu in Desi Ghee', quantityKg: 1, pricePerKg: 680, totalPrice: 680 },
    ],
    totalAmount: 2880,
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    orderStatus: 'New',
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(), // 15 mins ago
    notes: 'Please pack in golden gift box.',
  },
  {
    id: 'ORD-8941',
    customerName: 'Priya Verma',
    customerPhone: '+91 91234 56789',
    customerEmail: 'priya.v@gmail.com',
    deliveryAddress: 'House 14, Greater Kailash Part 1, New Delhi',
    items: [
      { id: '3', sweetName: 'Pista Rasgulla', quantityKg: 1.5, pricePerKg: 520, totalPrice: 780 },
      { id: '4', sweetName: 'Mathura Peda', quantityKg: 1, pricePerKg: 640, totalPrice: 640 },
    ],
    totalAmount: 1420,
    paymentMethod: 'Card',
    paymentStatus: 'Paid',
    orderStatus: 'Preparing',
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'ORD-8940',
    customerName: 'Amitabh Gupta',
    customerPhone: '+91 99887 76655',
    customerEmail: 'amit.gupta@techmail.com',
    deliveryAddress: 'Flat 501, Golf Course Road, Gurugram',
    items: [
      { id: '5', sweetName: 'Royal Sweets Hamper', quantityKg: 1, pricePerKg: 3500, totalPrice: 3500 },
    ],
    totalAmount: 3500,
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    orderStatus: 'Ready',
    createdAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
  },
  {
    id: 'ORD-8939',
    customerName: 'Sunita Aggarwal',
    customerPhone: '+91 97112 23344',
    customerEmail: 'sunita.agg@yahoo.com',
    deliveryAddress: 'A-12, Model Town, Delhi',
    items: [
      { id: '6', sweetName: 'Gulab Jamun Soft Dry', quantityKg: 2, pricePerKg: 480, totalPrice: 960 },
      { id: '7', sweetName: 'Crispy Saffron Jalebi', quantityKg: 1, pricePerKg: 540, totalPrice: 540 },
    ],
    totalAmount: 1500,
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Pending',
    orderStatus: 'Delivered',
    createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
];

export const INITIAL_FESTIVALS: FestivalCampaign[] = [
  {
    id: 'FEST-01',
    title: 'Diwali Royal Sweets Carnival',
    festivalName: 'Diwali Special',
    bannerUrl: 'https://images.unsplash.com/photo-1605197584547-c93e12564dd1?auto=format&fit=crop&q=80&w=1200',
    discountPercentage: 20,
    startDate: '2026-10-20',
    endDate: '2026-11-05',
    isActive: true,
    featuredProducts: ['Kaju Katli Special', 'Royal Sweets Hamper', 'Motichoor Laddu'],
    description: 'Celebrate Diwali with pure Desi Ghee authentic traditional sweets and custom engraved gift boxes.',
  },
  {
    id: 'FEST-02',
    title: 'Raksha Bandhan Sweetness Overflow',
    festivalName: 'Rakhi Special',
    bannerUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=1200',
    discountPercentage: 15,
    startDate: '2026-08-01',
    endDate: '2026-08-15',
    isActive: false,
    featuredProducts: ['Saffron Ghewar', 'Dry Fruit Box'],
    description: 'Express sibling love with handmade Saffron Ghewar and luxury sweet assortments.',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'CPN-1',
    code: 'FESTIVE100',
    discountPercent: 15,
    minOrderValue: 999,
    expiryDate: '2026-12-31',
    usageLimit: 500,
    timesUsed: 142,
    isActive: true,
  },
  {
    id: 'CPN-2',
    code: 'ROYAL20',
    discountPercent: 20,
    minOrderValue: 1999,
    expiryDate: '2026-09-30',
    usageLimit: 200,
    timesUsed: 89,
    isActive: true,
  },
  {
    id: 'CPN-3',
    code: 'WELCOME50',
    discountPercent: 10,
    minOrderValue: 499,
    expiryDate: '2026-12-31',
    usageLimit: 1000,
    timesUsed: 612,
    isActive: true,
  },
];

export const INITIAL_BOOKINGS: TableBooking[] = [
  {
    id: 'TB-101',
    customerName: 'Sanjay Malhotra',
    phone: '+91 98100 11223',
    email: 'sanjay.m@corporate.in',
    guestCount: 6,
    bookingDate: '2026-07-26',
    bookingTime: '07:30 PM',
    specialRequests: 'Sweets tasting platter arrangement for family celebration.',
    status: 'Confirmed',
    tableNumber: 'T-04 (VIP Family)',
  },
  {
    id: 'TB-102',
    customerName: 'Kavita Chawla',
    phone: '+91 99532 88990',
    email: 'kavita.c@gmail.com',
    guestCount: 2,
    bookingDate: '2026-07-26',
    bookingTime: '08:00 PM',
    specialRequests: 'Quiet corner table near sweet display fountain.',
    status: 'Pending',
  },
];

export const INITIAL_CUSTOMERS: CustomerCRM[] = [
  {
    id: 'CUST-1',
    name: 'Rajesh Sharma',
    phone: '+91 98765 43210',
    email: 'rajesh.s@gmail.com',
    totalOrders: 18,
    totalSpent: 34200,
    loyaltyPoints: 3420,
    tier: 'Platinum',
    lastOrderDate: '2026-07-25',
  },
  {
    id: 'CUST-2',
    name: 'Priya Verma',
    phone: '+91 91234 56789',
    email: 'priya.v@gmail.com',
    totalOrders: 9,
    totalSpent: 12800,
    loyaltyPoints: 1280,
    tier: 'Gold',
    lastOrderDate: '2026-07-25',
  },
  {
    id: 'CUST-3',
    name: 'Sunita Aggarwal',
    phone: '+91 97112 23344',
    email: 'sunita.agg@yahoo.com',
    totalOrders: 24,
    totalSpent: 48900,
    loyaltyPoints: 4890,
    tier: 'Platinum',
    lastOrderDate: '2026-07-24',
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'STF-1',
    name: 'Master Chef Rameshwar',
    email: 'rameshwar@aggarwalsweets.com',
    phone: '+91 98111 00001',
    role: 'Owner',
    department: 'Kitchen',
    status: 'Active',
    joinedDate: '2015-01-10',
    permissions: ['Full Access', 'Financials', 'Menu Override', 'Staff Control'],
  },
  {
    id: 'STF-2',
    name: 'Vikas Singhal',
    email: 'vikas.m@aggarwalsweets.com',
    phone: '+91 98111 00002',
    role: 'Manager',
    department: 'Management',
    status: 'Active',
    joinedDate: '2019-04-15',
    permissions: ['Orders', 'Menu Edit', 'Inventory', 'Coupons'],
  },
  {
    id: 'STF-3',
    name: 'Anil Kumar',
    email: 'anil.k@aggarwalsweets.com',
    phone: '+91 98111 00003',
    role: 'Staff',
    department: 'Billing',
    status: 'Active',
    joinedDate: '2022-09-01',
    permissions: ['Billing', 'Order Status Update'],
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'INV-1',
    name: 'Pure Desi Ghee (Verka / Amul)',
    category: 'Dairy & Mawa',
    stockQuantity: 180,
    unit: 'kg',
    minThreshold: 50,
    unitPrice: 620,
    supplierName: 'Amul Dairy Dist., Delhi',
    supplierPhone: '+91 98100 99887',
    lastRestocked: '2026-07-20',
  },
  {
    id: 'INV-2',
    name: 'Fresh Mawa (Khoya)',
    category: 'Dairy & Mawa',
    stockQuantity: 15, // Low stock trigger!
    unit: 'kg',
    minThreshold: 40,
    unitPrice: 380,
    supplierName: 'Mathura Milk Producers Co.',
    supplierPhone: '+91 98100 55443',
    lastRestocked: '2026-07-24',
  },
  {
    id: 'INV-3',
    name: 'Afghan Pistachios (Pista Kernel)',
    category: 'Dry Fruits',
    stockQuantity: 45,
    unit: 'kg',
    minThreshold: 20,
    unitPrice: 1800,
    supplierName: 'Khari Baoli Traders, Delhi',
    supplierPhone: '+91 98100 12345',
    lastRestocked: '2026-07-15',
  },
  {
    id: 'INV-4',
    name: 'Kashmiri Mogra Saffron (Kesar)',
    category: 'Spices & Flavors',
    stockQuantity: 0.8,
    unit: 'kg',
    minThreshold: 0.5,
    unitPrice: 240000,
    supplierName: 'Pampore Kesar Emporium',
    supplierPhone: '+91 99066 11223',
    lastRestocked: '2026-07-01',
  },
];

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: 'LOG-1',
    user: 'Vikas Singhal (Manager)',
    action: 'Updated status for Order #ORD-8941 to "Preparing"',
    timestamp: '10 mins ago',
    type: 'order',
  },
  {
    id: 'LOG-2',
    user: 'Master Chef Rameshwar',
    action: 'Restocked 180kg Pure Desi Ghee',
    timestamp: '2 hours ago',
    type: 'inventory',
  },
  {
    id: 'LOG-3',
    user: 'Anil Kumar',
    action: 'Created Coupon code "FESTIVE100"',
    timestamp: 'Yesterday',
    type: 'system',
  },
];
